config/routes.rb
    # sometimes we might pause our contract with IT-Recht when we don't sell any
    # tickets for a longer period of time
    # in that case we're legally obligated to remove their content from our site
    if Settings.hide_it_recht_content
      privacy_redirect = redirect('datenschutz', status: 302)
      get 'agb', to: privacy_redirect
      get 'widerrufsbelehrung', as: :widerruf, to: privacy_redirect
      get 'datenschutz', action: :privacy_fallback, as: :privacy
    else
      get 'agb'
      get 'widerrufsbelehrung', action: :widerruf, as: :widerruf
      get 'datenschutz', action: :privacy, as: :privacy
    end

    root action: :index
  end

  scope controller: :sessions do
    get 'login', action: :new, as: :login
    post 'login', action: :create
    get 'logout', action: :destroy, as: :logout
  end

  scope controller: :web_authn, as: :web_authn, path: 'webauthn' do
    get :options_for_create
    post :create
    get :options_for_auth
    post :auth
    delete ':id', action: :destroy, as: :destroy
  end

  direct(:eu_dispute_resolution) { 'https://ec.europa.eu/consumers/odr' }

  # resources
  scope path_names: { new: 'neu', edit: 'bearbeiten' } do
    resources :contact_messages, only: %i[index create], path: 'kontakt'

    # galleries
    resources :galleries, path: 'galerie', except: :show do
      resources :photos, path: 'fotos', only: %i[create edit update destroy] do
        put :update_positions, on: :collection
      end
    end

    resource :newsletter_subscriber, path: :newsletter, only: %i[new create edit update destroy],
                                     path_names: { new: 'anmelden' } do
      get :confirm
    end

    namespace :admin, path: 'vorstand' do
      resources :newsletters do
        post :finish, on: :member
        post :approve, on: :member
        resources :images, controller: :newsletter_images,
                           only: %i[create destroy]
      end
      resources :members_members, path: 'mitglieder', controller: :members do
        patch :reactivate, on: :member
        patch :resume_membership_fee_payments, on: :member
      end
      resources :members_membership_fee_payments,
                controller: :membership_fee_payments do
        patch :mark_as_failed, on: :member
      end
      resources :members_membership_fee_debit_submissions,
                path: 'mitgliedsbeitrag-lastschrifteinreichungen',
                controller: :membership_fee_debit_submissions, only: %i[index show]
      resources :members_membership_applications, path: 'mitgliedsanträge', controller: :membership_applications,
                                                  only: %i[index show destroy]
      get 'wasserwerk' => 'wasserwerk#index'
      patch 'wasserwerk' => 'wasserwerk#update'
      get 'logo-generator' => '/static#logo_generator'
    end

    namespace :ticketing, path: '' do
      concern :ticketable do
        resource :tickets, only: [] do
          collection do
            patch :cancel, path: 'stornieren'
            get :transfer, path: 'umbuchen'
            get :edit, path: 'bearbeiten'
            patch :update
            post :init_transfer
            patch :finish_transfer
            get :printable
          end
        end
      end

      scope path: 'vorverkauf' do
        scope controller: :statistics, path: 'statistik', as: :statistics do
          get 'seats/:date_id', action: :seats, as: :seats
          get 'chart_data', action: :chart_data, as: :chart_data
          get 'map_data', action: :map_data, as: :map_data
          get '/(:slug)', action: :index
        end
        scope path: 'bestellungen' do
          resource :order, path: '', only: [] do
            member do
              get 'neu/(:event_slug)', action: :new_privileged,
                                       as: :new_privileged
            end
            collection do
              post 'enable-reservation-groups',
                   action: :enable_reservation_groups,
                   as: :enable_reservation_groups
            end
          end
          resources :orders, path: '', only: %i[index show edit update],
                             concerns: :ticketable do
            member do
              post :send_pay_reminder
              post :resend_confirmation
              patch :mark_as_paid
              post :resend_items
              get :seats
            end
          end
        end
        scope controller: :payments, path: 'zahlungen', as: :payments do
          get '/', action: :index
          patch :mark_as_paid
          post :submit_transactions
          get :bank_submission_file, path: 'bank-submission/:id'
        end
        resources :billings, only: %i[create]
        resources :seatings, path: 'sitzpläne', only: %i[index show]
        resources :reservation_groups, only: %i[index show create update destroy]
        resources :coupons, path: 'gutscheine' do
          post :mail, on: :member
        end
        resources :events, except: %i[destroy] do
          resources :event_dates, except: %i[index show]
          resources :ticket_types, except: %i[index show]
        end
      end

      namespace :box_office, path: 'ticketing/box_office' do
        resources :purchases, param: :token, only: [] do
          get :show, on: :member
        end

        get 'front_display' => 'front_display#index'
      end
    end

    scope path: 'tickets', module: :ticketing do
      get 'bestellen/(:event_slug)' => 'orders#new', as: :new_ticketing_order, type: :web

      max_length = Ticketing::SigningKey.max_info_length
      info_regex = /[A-Za-z0-9\-_]{1,#{max_length}}/

      scope path: ':signed_info', constraints: { signed_info: info_regex }, module: :customer, as: :customer do
        scope controller: :orders, as: :order_overview do
          get '/', action: :show
          post '/', action: :check_email
          get '/tickets(/:id)', action: :tickets, as: :tickets
          get '/seats', action: :seats
        end

        scope controller: :ticket_transfer, path: 'umbuchen', as: :ticket_transfer do
          get '/', action: :index
          post :init
          patch :finish
        end

        scope controller: :cancellation, path: 'stornieren', as: :cancellation do
          get '/', action: :index
          post :refund
          post '/', action: :cancel
        end
      end
    end

    get 'geschenkgutscheine/bestellen' => 'ticketing/orders#new_coupons', as: :new_coupons_ticketing_order, type: :web

    namespace :members, path: 'mitglieder' do
      resource :member, path: 'mitgliedschaft', controller: :member, only: %i[edit update] do
        member do
          get 'aktivieren', action: :activate, as: :activate
          patch :finish_activation
          get 'passwort-vergessen', action: :forgot_password, as: :forgot_password
          post :finish_forgot_password
          get 'passwort-zuruecksetzen', action: :reset_password, as: :reset_password
          patch :finish_reset_password
        end
      end

      scope controller: :dashboard do
        get '/', action: :index, as: :root
      end

      resources :membership_applications, path: 'antrag', path_names: { new: '' }, only: %i[new create]
    end
  end

  scope path: :api, as: :api, defaults: { format: :json } do
    scope module: :api do
      namespace :ticketing do
        resources :orders, only: [:create] do
          post :totals, on: :collection
          get :retail_printable, on: :member
        end

        namespace :box_office do
          resources :events, only: :index
          resources :products, only: :index
          resources :orders, only: %i[index show create destroy]
          resources :tickets, only: [] do
            collection do
              get :show, constraints: { format: :pdf }
              patch :update
            end
          end
          resources :purchases, only: :create
          resource :seating, only: :show, defaults: { format: :html }
          resources :transactions, only: %i[index create]
        end

        resources :check_ins, only: %i[index create]

        namespace :check_ins do
          resources :orders, only: %i[index] do
            post :mark_as_paid, on: :member
          end
        end

        namespace :node do
          resources :events, only: :index
        end

        namespace :push_notifications do
          resources :subscriptions, only: :create
        end
      end

      resources :members, only: %i[index show]

      scope path: :mobile_devices, controller: :mobile_devices do
        get :profile, as: :mobile_device_profile
        post :enroll, as: :enroll_mobile_device
      end
    end

    passbook_routes
  end

  scope controller: :shared_email_accounts, path: :shared_email_accounts do
    get :authorize, action: :token
    get 'credentials/:token', action: :credentials
  end

  resources :internet_access_sessions, path: :wlan, only: %i[new create],
                                       path_names: { new: '' }

  get 'backstage-tv' => 'backstage_tv#index'

  use_doorkeeper do
    controllers token_info: 'doorkeeper/enhanced_token_info'
    skip_controllers :applications, :authorized_applications
  end

  scope path: :admin do
    require 'sidekiq/web'
    if Rails.env.production?
      Sidekiq::Web.use Rack::Auth::Basic do |username, password|
        credentials = Rails.application.credentials.sidekiq
        ActiveSupport::SecurityUtils.secure_compare(
          Digest::SHA256.hexdigest(username),
          Digest::SHA256.hexdigest(credentials.dig(:web, :username) ||
                                     SecureRandom.hex)
        ) &&
          ActiveSupport::SecurityUtils.secure_compare(
            Digest::SHA256.hexdigest(password),
            Digest::SHA256.hexdigest(credentials.dig(:web, :password) ||
                                       SecureRandom.hex)
          )
      end
    end
    mount Sidekiq::Web, at: 'sidekiq'
  end

  get 'up' => 'health#show'
end

app/controllers/api/ticketing/box_office/orders_controller.rb
# frozen_string_literal: true

module Api
  module Ticketing
    module BoxOffice
      class OrdersController < BaseController
        include OrderCreation

        before_action :find_order, only: :destroy

        helper ::Ticketing::TicketingHelper

        def index
          @orders = ::Ticketing::Order.with_tickets.order(:last_name, :first_name)
          return @orders = @orders.none unless params.keys.intersect?(%w[date_imminent unpaid recent q])

          @orders = @orders.date_imminent if params[:date_imminent].present?
          @orders = @orders.unpaid if params[:unpaid].present?
          @orders = recent_orders if params[:recent].present?
          @orders, @ticket = search_orders if params[:q].present?
        end

        def show
          @order = ::Ticketing::Order.find(params[:id])
        end

        def create
          create_order
          return unless order_errors?

          head :bad_request
        end

        def destroy
          return head :forbidden unless @order.is_a? ::Ticketing::BoxOffice::Order

          ::Ticketing::OrderDestroyService.new(@order).execute
          head :no_content
        end

        private

        def find_order
          @order = ::Ticketing::Order.find(params[:id])
        end

        def recent_orders
          @orders.where(box_office_id: current_box_office).order(created_at: :desc).limit(30)
        end

        def search_orders
          ::Ticketing::OrderSearchService.new(
            params[:q],
            scope: @orders
          ).execute
        end

        def order_params
          params[:type] = :box_office
          params.permit(
            :type, :box_office_id, :socket_id,
            order: [
              :date,
              { tickets: {} }
            ]
          )
        end
      end
    end
  end
end

app/controllers/api/ticketing/check_ins/orders_controller.rb
# frozen_string_literal: true

module Api
  module Ticketing
    module CheckIns
      class OrdersController < ApiController
        include Authenticatable

        def index
          @orders = ::Ticketing::Order.with_tickets.date_imminent
        end

        def mark_as_paid
          order = ::Ticketing::Order.find(params[:id])
          ::Ticketing::OrderPaymentService.new(order).mark_as_paid
          head :ok
        end

        private

        def auth_token
          super || Rails.application.credentials.ticketing_api_auth_token
        end
      end
    end
  end
end

app/controllers/api/ticketing/orders_controller.rb
# frozen_string_literal: true

module Api
  module Ticketing
    class OrdersController < ApiController
      include OrderCreation
      include ::Ticketing::OrderingType

      prepend_before_action :authorize_type

      helper ::Ticketing::TicketingHelper

      def create
        return head :not_found unless type.in? %i[web admin retail]

        create_order
        return render status: :bad_request, json: errors_response if order_errors?

        suppress_in_production(StandardError) do
          create_newsletter_subscriber
        end

        set_flash_notice
      end

      def totals
        @result = ::Ticketing::OrderSimulationService.new(
          simulation_params.to_h
        ).execute
      end

      def retail_printable
        order = ::Ticketing::Retail::Order.find_signed!(params[:id])
        send_data order.printable.render, type: 'application/pdf', disposition: 'inline'
      end

      private

      def errors_response
        {
          errors: order_create_service.errors.map do |error|
            {
              key: error,
              message: t("ticketing.orders.errors.#{error}", default: nil)
            }
          end
        }
      end

      def order_params
        params.permit(
          :type, :newsletter, :socket_id,
          order: [
            :date,
            {
              tickets: {},
              coupons: %i[value number],
              coupon_codes: [],
              address: %i[
                email first_name gender last_name affiliation phone plz
              ],
              payment: %i[method name iban stripe_payment_method_id]
            }
          ]
        )
      end

      def simulation_params
        params.permit(:event_id, :socket_id,
                      tickets: {}, coupons: %i[value number], coupon_codes: [])
      end

      def create_newsletter_subscriber
        return unless web? && params[:newsletter].present?

        Newsletter::SubscriberCreateService.new(newsletter_params,
                                                after_order: true).execute
      end

      def newsletter_params
        subscriber_params = @order.slice(:email, :gender, :last_name)
        subscriber_params[:privacy_terms] = true
        subscriber_params
      end

      def set_flash_notice
        return unless admin?

        key = ".created#{'_email' if @order.email.present?}"
        flash.notice = t(key)
      end

      def authorize_type
        return if type.blank? || web? || admin_action_authorized? ||
                  retail_action_authorized?

        deny_access root_path
      end

      def admin_action_authorized?
        admin? && current_user&.admin?
      end

      def retail_action_authorized?
        retail? && current_user&.retail?
      end
    end
  end
end

app/helpers/ticketing/customer/orders_helper.rb
# frozen_string_literal: true

module Ticketing
  module Customer
    module OrdersHelper
      WALLET_PATTERN = /(Android|iP(hone|ad|od)|OS X|Windows Phone)/

      def structured_data(order)
        tag.script type: 'application/ld+json' do
          raw render(partial: 'ticketing/customer/orders/structured_data', formats: :json, locals: { order: }) # rubocop:disable Rails/OutputSafety
        end
      end

      def reservation_status(ticket)
        schema_prefixed(ticket.cancelled? ? 'ReservationCancelled' : 'ReservationConfirmed')
      end

      def order_url(order)
        customer_order_overview_url(order.signed_info(authenticated: true))
      end

      def schema_prefixed(entity)
        "#{schema_context}/#{entity}"
      end

      def schema_context
        'http://schema.org'
      end

      def wallet_supported?
        @wallet_supported ||= request.user_agent&.match?(WALLET_PATTERN)
      end

      def wallet_pass_bundle_available?(order)
        order.tickets.count <= 10 # Apple only supports a maximum of 10 passes per bundle
      end
    end
  end
end

app/helpers/ticketing/customers/orders_helper.rb
# frozen_string_literal: true

module Ticketing
  module Customers
    module OrdersHelper
      def structured_data(order)
        tag.script type: 'application/ld+json' do
          raw render(partial: 'ticketing/customers/orders/structured_data', formats: :json, locals: { order: }) # rubocop:disable Rails/OutputSafety
        end
      end

      def reservation_status(ticket)
        schema_prefixed(ticket.cancelled? ? 'ReservationCancelled' : 'ReservationConfirmed')
      end

      def order_url(order)
        order_overview_url(order.signed_info(authenticated: true))
      end

      def schema_prefixed(entity)
        "#{schema_context}/#{entity}"
      end

      def schema_context
        'http://schema.org'
      end
    end
  end
end

app/helpers/ticketing/orders_helper.rb
# frozen_string_literal: true

module Ticketing
  module OrdersHelper
    def max_tickets_for_type(max_tickets, type)
      return max_tickets unless type.exclusive? && !current_user.admin?

      type.credit_left_for_member(current_user)
    end

    def redeemed_coupon_list(order)
      return tag.em(t('application.none')) if order.redeemed_coupons.none?

      safe_join(order.redeemed_coupons.map do |coupon|
        link_to_if(policy(coupon).show?, coupon.recipient.presence || "##{coupon.id}", coupon)
      end, ', ')
    end
  end
end

app/views/ticketing/customers/orders/_refund.html.slim
- if @transferable
  hr
  h2.hcen Umbuchung Ihrer Tickets
  p Sie haben die Möglichkeit Ihre Tickets auf ein anderes Datum #{@event.seating.plan? ? 'und/oder einen anderen Sitzplatz ' : '' }umzubuchen. Klicken Sie dazu bitte auf folgenden Link:
  p.hcen = link_to 'Tickets umbuchen', ticket_transfer_path
  p Gerne erreichen Sie uns bei weiteren Fragen oder besonderen Umbuchungswünschen auch auf folgenden Wegen:<br>
  p.hcen
    <b>(02653) 28 27 09</b><br>
    = mail_to('info@theater-kaisersesch.de')

- if @order_refundable
  hr
  h2.hcen Stornierung Ihrer Tickets
  p
    - if @transferable
      ' Falls eine Umbuchung für Sie nicht infrage kommt, können Sie Ihre Tickets selbstverständlich auch stornieren.
    | Bei einer Stornierung wird Ihnen der volle Ticketpreis erstattet. Bitte geben Sie dazu im Folgenden ein Konto an, auf das wir den Betrag zurücküberweisen können.

  = form_with url: order_overview_refund_path(params[:signed_info]), method: :post, local: true, class: :refund, data: { controller: 'ticketing--refund', bank_charge: @order.charge_payment? } do |f|
    - if @order.charge_payment?
      table
        tr
          td = f.radio_button :use_bank_charge, true, required: true,
            data: { action: 'ticketing--refund#toggleBankDetails' }
          td
            = f.label :use_bank_charge, value: true
              | Bankkonto der ursprünglichen Lastschrift verwenden
              .small Kontoinhaber: #{@order.bank_charge&.name}
              .small IBAN: #{obfuscated_iban(@order.bank_charge&.iban)}
        tr
          td = f.radio_button :use_bank_charge, false, required: true,
            data: { action: 'ticketing--refund#toggleBankDetails' }
          td = f.label :use_bank_charge, value: false
            | Anderes Bankkonto verwenden

    table data-target='ticketing--refund.bankDetails' class=('visible' unless @order.charge_payment?)
      tr
        td = f.label :name, 'Kontoinhaber:'
        td = f.text_field :name
      tr
        td = f.label :iban, 'IBAN:'
        td = f.text_field :iban

    p.hcen = f.submit 'Erstattung beantragen'

app/views/ticketing/customers/orders/email_form.html.slim
- title 'Ihre Bestellung'

.container
  h1 Ihre Bestellung

  .row: .col
    p Um zu Ihrer Bestellübersicht zu gelangen, geben Sie bitte die E-Mail-Adresse ein, mit der diese Bestellung aufgegeben wurde.
    .card
      = form_with url: order_overview_path(params[:signed_info]), method: :post do |f|
        = render 'form_field', form: f, attribute: :email, label: 'E-Mail-Adresse'
          = f.email_field :email
        .text-center = submit_tag :absenden, class: :btn

app/views/ticketing/customers/orders/show.html.slim
- title "Bestellung #{@order.number}"

- if @order.tickets.any?
  = structured_data @order

.container
  h1 Ihre Bestellung

  .row: .col: .card: dl.md-horizontal
    dt Nummer
    dd: tt = @order.number
    dt aufgegeben am
    dd = l(@order.created_at, format: :long)
    - if @order.is_a? Ticketing::Web::Order
      dt Name
      dd #{@order.first_name} #{@order.last_name}
      dt E-Mail-Addresse
      dd = @order.email
      dt Zahlungsart
      dd = order_pay_method(@order)
      dt bezahlt
      dd = @order.paid ? 'ja' : 'nein'

  - if @order.anonymized?
    .row: .col = render 'alert', type: :warning
      | Diese Bestellung wurde gemäß unserer #{link_to 'Datenschutzerklärung', privacy_path} nach Ablauf der Aufbewahrungsfrist anonymisiert. Die Bestelldetails sind daher nicht mehr einsehbar.

  - else
    - if @order.tickets.any?
      h2 Bestellte Tickets
      .row: .col.w-100
        - if @order.date.cancelled?
          = render 'alert', type: :warning
            | Bitte beachten Sie, dass Ihr gebuchter Termin leider entfällt.
            - if @transferable || @cancellable
              |< Sie haben die Möglichkeit einer
              - if @transferable && @cancellable
                |< Umbuchung oder Stornierung
              - elsif @transferable
                |< Umbuchung
              - else
                |< Stornierung
              |< Ihrer Tickets.
        .card: .table-responsive: table
          thead
            tr
            tr
              th Nummer
              th Termin
              th Kategorie
              th Sitz
          tbody
            - @order.tickets.each do |ticket|
              - classes = [:cancelled] if ticket.cancelled?
              tr class=classes
                td
                  tt = ticket.number
                  - if show_wallet? && !ticket.cancelled?
                    .mt-1 = link_to order_overview_wallet_path(ticket.signed_info(authenticated: true))
                      = image_tag('add_to_wallet.svg')
                td class=('cancelled' if !ticket.cancelled? && ticket.date.cancelled?)
                  | „#{ticket.event.name}“<br>
                  .small = l ticket.date.date, format: :long_weekday
                  - if !ticket.cancelled? && ticket.date.cancelled?
                    .text-red Termin entfällt
                td
                  = ticket.type.name
                  .small = number_to_currency ticket.price
                td
                  - if ticket.seat.present?
                    = ticket.seat.full_number
                  - else
                    | Freie Platzwahl

        - unless @order.anonymized?
          - if @order.is_a?(Ticketing::Web::Order)
            - if @transferable
              .text-center.mt-2
                = link_to 'Umbuchung', ticket_transfer_path, class: :btn
          - else
            .mt-1 = render 'alert', type: :info
              | Da Ihre Bestellung nicht online aufgegeben wurde, ist eine Umbuchung oder Stornierung nur über unsere Hotline möglich.
              .mt-1 Rufen Sie uns diesbezüglich gerne an: <b>(02653) 28 27 09</b>.

      - if @order.tickets.first.seat.present? && @order.date.future?
        h2 Sitzplätze
        .row: .col.w-100
          .card = render 'application/ticketing/seating', event: @order.event, seats_path: order_overview_seats_path(params[:signed_info]), class: %i[chosen]

    - if @order.purchased_coupons.any?
      h2 Bestellte Geschenkgutscheine
      .row: .col: .card: ul
        - @order.purchased_coupons.each do |coupon|
          li Gutschein über <b>#{number_to_currency(coupon.initial_value)}</b> (<tt>#{coupon.code}</tt>)

- unless @order.anonymized?
  - if @order.is_a?(Ticketing::Web::Order)
    - if @cancellable
      hr
      .container: .row: .col = render 'cancel' if @cancellable