config/routes.rb
    # sometimes we might pause our contract with IT-Recht when we don't sell any
    # tickets for a longer period of time
    # in that case we're legally obligated to remove their content from our site
    if Settings.hide_it_recht_content
      privacy_redirect = redirect('datenschutz', status: 302)
      get 'agb', to: privacy_redirect
      get 'widerrufsbelehrung', as: :widerruf, to: privacy_redirect
      get 'datenschutz', action: :privacy_fallback, as: :privacy
    else
      get 'agb'
      get 'widerrufsbelehrung', action: :widerruf, as: :widerruf
      get 'datenschutz', action: :privacy, as: :privacy
    end

    root action: :index
  end

  scope controller: :sessions do
    get 'login', action: :new, as: :login
    post 'login', action: :create
    get 'logout', action: :destroy, as: :logout
  end

  scope controller: :web_authn, as: :web_authn, path: 'webauthn' do
    get :options_for_create
    post :create
    get :options_for_auth
    post :auth
    delete ':id', action: :destroy, as: :destroy
  end

  direct(:eu_dispute_resolution) { 'https://ec.europa.eu/consumers/odr' }

  # resources
  scope path_names: { new: 'neu', edit: 'bearbeiten' } do
    resources :contact_messages, only: %i[index create], path: 'kontakt'

    # galleries
    resources :galleries, path: 'galerie', except: :show do
      resources :photos, path: 'fotos', only: %i[create edit update destroy] do
        put :update_positions, on: :collection
      end
    end

    resource :newsletter_subscriber, path: :newsletter, only: %i[new create edit update destroy],
                                     path_names: { new: 'anmelden' } do
      get :confirm
    end

    namespace :admin, path: 'vorstand' do
      resources :newsletters do
        post :finish, on: :member
        post :approve, on: :member
        resources :images, controller: :newsletter_images,
                           only: %i[create destroy]
      end
      resources :members_members, path: 'mitglieder', controller: :members do
        patch :reactivate, on: :member
        patch :resume_membership_fee_payments, on: :member
      end
      resources :members_membership_fee_payments,
                controller: :membership_fee_payments do
        patch :mark_as_failed, on: :member
      end
      resources :members_membership_fee_debit_submissions,
                path: 'mitgliedsbeitrag-lastschrifteinreichungen',
                controller: :membership_fee_debit_submissions, only: %i[index show]
      resources :members_membership_applications, path: 'mitgliedsanträge', controller: :membership_applications,
                                                  only: %i[index show destroy]
      get 'wasserwerk' => 'wasserwerk#index'
      patch 'wasserwerk' => 'wasserwerk#update'
      get 'logo-generator' => '/static#logo_generator'
    end

    namespace :ticketing, path: '' do
      concern :ticketable do
        resource :tickets, only: [] do
          collection do
            patch :cancel, path: 'stornieren'
            get :transfer, path: 'umbuchen'
            get :edit, path: 'bearbeiten'
            patch :update
            post :init_transfer
            patch :finish_transfer
            get :printable
          end
        end
      end

      scope path: 'vorverkauf' do
        scope controller: :statistics, path: 'statistik', as: :statistics do
          get 'seats/:date_id', action: :seats, as: :seats
          get 'chart_data', action: :chart_data, as: :chart_data
          get 'map_data', action: :map_data, as: :map_data
          get '/(:slug)', action: :index
        end
        scope path: 'bestellungen' do
          resource :order, path: '', only: [] do
            member do
              get 'neu/(:event_slug)', action: :new_privileged,
                                       as: :new_privileged
            end
            collection do
              post 'enable-reservation-groups',
                   action: :enable_reservation_groups,
                   as: :enable_reservation_groups
            end
          end
          resources :orders, path: '', only: %i[index show edit update],
                             concerns: :ticketable do
            member do
              post :send_pay_reminder
              post :resend_confirmation
              patch :mark_as_paid
              post :resend_items
              get :seats
            end
          end
        end
        scope controller: :payments, path: 'zahlungen', as: :payments do
          get '/', action: :index
          patch :mark_as_paid
          post :submit_transactions
          get :bank_submission_file, path: 'bank-submission/:id'
        end
        resources :billings, only: %i[create]
        resources :seatings, path: 'sitzpläne', only: %i[index show]
        resources :reservation_groups, only: %i[index show create update destroy]
        resources :coupons, path: 'gutscheine' do
          post :mail, on: :member
        end
        resources :events, except: %i[destroy] do
          resources :event_dates, except: %i[index show]
          resources :ticket_types, except: %i[index show]
        end
      end

      namespace :box_office, path: 'ticketing/box_office' do
        resources :purchases, param: :token, only: [] do
          get :show, on: :member
        end

        get 'front_display' => 'front_display#index'
      end
    end

    scope path: 'tickets', module: :ticketing do
      get 'bestellen/(:event_slug)' => 'orders#new', as: :new_ticketing_order, type: :web

      max_length = Ticketing::SigningKey.max_info_length
      info_regex = /[A-Za-z0-9\-_]{1,#{max_length}}/

      scope path: ':signed_info', constraints: { signed_info: info_regex }, module: :customer, as: :customer do
        scope controller: :orders, as: :order_overview do
          get '/', action: :show
          post '/', action: :check_email
          get '/tickets(/:id)', action: :tickets, as: :tickets
          get '/seats', action: :seats
        end

        scope controller: :ticket_transfer, path: 'umbuchen', as: :ticket_transfer do
          get '/', action: :index
          post :init
          patch :finish
        end

        scope controller: :cancellation, path: 'stornieren', as: :cancellation do
          get '/', action: :index
          post :refund
          post '/', action: :cancel
        end
      end
    end

    get 'geschenkgutscheine/bestellen' => 'ticketing/orders#new_coupons', as: :new_coupons_ticketing_order, type: :web

    namespace :members, path: 'mitglieder' do
      resource :member, path: 'mitgliedschaft', controller: :member, only: %i[edit update] do
        member do
          get 'aktivieren', action: :activate, as: :activate
          patch :finish_activation
          get 'passwort-vergessen', action: :forgot_password, as: :forgot_password
          post :finish_forgot_password
          get 'passwort-zuruecksetzen', action: :reset_password, as: :reset_password
          patch :finish_reset_password
        end
      end

      scope controller: :dashboard do
        get '/', action: :index, as: :root
      end

      resources :membership_applications, path: 'antrag', path_names: { new: '' }, only: %i[new create]
    end
  end

  scope path: :api, as: :api, defaults: { format: :json } do
    scope module: :api do
      namespace :ticketing do
        resources :orders, only: [:create] do
          post :totals, on: :collection
          get :retail_printable, on: :member
        end

        namespace :box_office do
          resources :events, only: :index
          resources :products, only: :index
          resources :orders, only: %i[index show create destroy]
          resources :tickets, only: [] do
            collection do
              get :show, constraints: { format: :pdf }
              patch :update
            end
          end
          resources :purchases, only: :create
          resource :seating, only: :show, defaults: { format: :html }
          resources :transactions, only: %i[index create]
        end

        resources :check_ins, only: %i[index create]

        namespace :check_ins do
          resources :orders, only: %i[index] do
            post :mark_as_paid, on: :member
          end
        end

        namespace :node do
          resources :events, only: :index
        end

        namespace :push_notifications do
          resources :subscriptions, only: :create
        end
      end

      resources :members, only: %i[index show]

      scope path: :mobile_devices, controller: :mobile_devices do
        get :profile, as: :mobile_device_profile
        post :enroll, as: :enroll_mobile_device
      end
    end

    passbook_routes
  end

  scope controller: :shared_email_accounts, path: :shared_email_accounts do
    get :authorize, action: :token
    get 'credentials/:token', action: :credentials
  end

  resources :internet_access_sessions, path: :wlan, only: %i[new create],
                                       path_names: { new: '' }

  get 'backstage-tv' => 'backstage_tv#index'

  use_doorkeeper do
    controllers token_info: 'doorkeeper/enhanced_token_info'
    skip_controllers :applications, :authorized_applications
  end

  scope path: :admin do
    require 'sidekiq/web'
    if Rails.env.production?
      Sidekiq::Web.use Rack::Auth::Basic do |username, password|
        credentials = Rails.application.credentials.sidekiq
        ActiveSupport::SecurityUtils.secure_compare(
          Digest::SHA256.hexdigest(username),
          Digest::SHA256.hexdigest(credentials.dig(:web, :username) ||
                                     SecureRandom.hex)
        ) &&
          ActiveSupport::SecurityUtils.secure_compare(
            Digest::SHA256.hexdigest(password),
            Digest::SHA256.hexdigest(credentials.dig(:web, :password) ||
                                       SecureRandom.hex)
          )
      end
    end
    mount Sidekiq::Web, at: 'sidekiq'
  end

  get 'up' => 'health#show'
end

app/views/info/_event_gatte.html.slim
.section
  h2 Vorverkauf

  = question_answer 'Wo erhalte ich Tickets?' do
    | Tickets können Sie bequem von zu Hause aus #{link_to 'online', new_ticketing_order_path} bestellen oder Sie besuchen eine unserer folgenden Vorverkaufsstellen:
    ul
      li: a href='https://buchhandlung-walgenbach.de' Buchhandlung Walgenbach, Kaisersesch
      li: a href='http://layaa.de' Buchhandlung Layaa-Laulhé, Cochem

  = question_answer 'Gibt es Platzreservierungen?' do
    | Ja, jedes Ticket ist an einen Sitzplatz gebunden, den Sie bei Ihrer Online-Bestellung anhand unseres Sitzplans frei wählen können.

  = question_answer 'Gibt es gehbehindertengerechte Sitzplätze?' do
    | Ja, bitte melden Sie sich dazu bitte bei unserer Hotline: <b>(02653) 28 27 09</b>.

  = question_answer 'Welche Zahlungsarten stehen mir bei der Online-Bestellung zur Verfügung?' do
    | Wir akzeptieren SEPA-Lastschrift und Zahlungen per Überweisung.

  = question_answer 'Wie erhalte ich meine Tickets, die ich online bestellt habe?' do
    | Sofern Sie Zahlung per Lastschrift gewählt haben, werden Ihnen Ihre Tickets umgehend nach Ihrer Bestellung per E-Mail zugesandt. Bei Vorkasse per Überweisung erhalten Sie Ihre Tickets nach Zahlungseingang.
    p Im Anhang der E-Mail finden Sie ein PDF-Dokument, das Ihre Tickets enthält. Dieses können Sie sich ausdrucken, um es am Abend der Aufführung bei der Einlasskontrolle vorzuzeigen.

  = question_answer 'Kann ich meine Tickets auch auf einem Handy vorzeigen?' do
    | Selbstverständlich. Zeigen Sie dazu einfach das PDF-Dokument auf Ihrem Handy-Display vor.
    p Falls Sie ein iPhone besitzen, haben Sie alternativ auch die Möglichkeit, Ihre Tickets in der vorinstallierten App „Wallet“ zu hinterlegen. Nutzen Sie dazu einfach den Button in der Bestätigungs-E-Mail oder scannen Sie den Barcode auf Ihrem Ticket. Unter Android ist dies mit der App „#{link_to 'Wallet Passes', 'https://play.google.com/store/apps/details?id=io.walletpasses.android', target: '_blank'}“ möglich.

  = question_answer 'Lassen sich Tickets umbuchen oder stornieren?' do
    p Sitzplätze lassen sich jederzeit umbuchen.
    p Stornierungen sind bis 24 Stunden vor Beginn der Veranstaltung möglich. Selbstverständlich erhalten Sie den vollen Betrag der stornierten Tickets zurück.
    p Umbuchungen oder Stornierungen können Sie selbst über den Link in Ihrer Bestellbestätigungs-E-Mail oder telefonisch unter <b>(02653) 28 27 09</b> vornehmen.

.section
  h2 Anfahrt

  = render 'info/map'

  = question_answer 'Wo finde ich die Freilichtbühne?' do
    | Unser Freilichttheater findet im Historischen Ortskern von Kaisersesch statt. Dieser befindet sich in der Burgstraße, direkt an der Hauptstraße, bzw. neben der Kirche.
    p Im Ort sollte Ihnen unser namensgebender Kirchturm eine gute Orientierungshilfe sein.

  = question_answer 'Wie reise ich mit dem Auto an?' do
    | Über die Autobahn A48 kommend fahren Sie an der Abfahrt Kaisersesch ab und folgen der Beschilderung bis Kaisersesch. Circa 200 Meter nach Ortseingang finden Sie rechts hinter dem Busbahnhof den Parkplatz „Balduinplatz“.
    p Weitere Parkmöglichkeiten sind in der obigen Karte markiert.

  = question_answer 'Wie reise ich mit öffentlichen Verkehrsmitteln an?' do
    | Möchten Sie mit der Bahn anreisen, fahren Sie von Andernach kommend mit der Regionalbahn der DB Regio bis zum Bahnhof Kaisersesch. Von dort folgen Sie der Bahnhofstraße abwärts in den Ort bis zum Zentralplatz (Sparkasse).
    p Mit dem Bus fahren Sie bis zum Balduinplatz.

.section
  h2 Wetter

  = question_answer 'Was passiert, wenn am Aufführungstag schlechtes Wetter herrscht?' do
    | Grundsätzlich versuchen wir bei jeder Wetterlage zu spielen. Sollte das Wetter derart schlecht sein, dass wir die Aufführung schon im Vorfeld absagen oder in der ersten Hälfte des Stücks abbrechen müssen, haben Sie selbstverständlich ein Recht auf Erstattung Ihres Eintrittsgeldes.
    p Bitte prüfen Sie an Aufführungstagen mit schlechtem Wetter unsere Homepage, die wir laufend mit aktuellen Informationen versorgen werden.

  = question_answer 'Sind die Zuschauerränge überdacht?' do
    | Leider nicht. Wir bitten Sie daher, gegebenenfalls an wetterfeste Kleidung zu denken. Gerne erhalten Sie vor Ort aber auch Regenponchos.

.section
  h2 Aufführung

  = question_answer 'Ich habe Tickets kurzfristig abzugeben. Kann ich diese an der Abendkasse zurückgeben?'
    | Ja, das ist möglich. Sofern wir einen neuen Besitzer für Ihre Tickets finden können, erhalten Sie den vollen Betrag zurück.

  = question_answer 'Kann ich an der Abendkasse mit EC- oder Kreditkarte bezahlen?'
    | Ja, das ist möglich, gerne auch bei kleinen Beträgen. Kontaktlose Zahlungen akzeptieren wir ebenfalls.
    p Bitte beachten Sie, dass die Essens- und Getränkestände hingegen nur Bargeld akzeptieren.

  = question_answer 'Werden vor Ort Speisen und Getränke angeboten?'
    | Ja, an unseren Ständen bieten wir gepflegte Getränke und leckere Kleinigkeiten an.

  = question_answer 'Wird es eine Pause geben?' do
    | Nach der ersten Hälfte des Stücks werden wir eine Pause von etwa 30 Minuten einlegen. In dieser Zeit sind unsere Essens- und Getränkestände für Sie geöffnet.

  = question_answer 'Wie lange dauert die Aufführung?' do
    | Die Aufführung dauert etwa 120 Minuten (exklusive Pause).

  = question_answer 'Kann ich während der Aufführung fotografieren oder filmen?' do
    | Leider können wir Ihnen dies nicht gestatten.

  = question_answer 'Gibt es ein Rauchverbot?' do
    | Rauchen ist während der Aufführung nicht gestattet.

  = question_answer 'Werden Sitzkissen zur Ausleihe gestellt?' do
    | Leider stehen keine Sitzkissen zur Ausleihe zur Verfügung. Gerne können Sie sich eigene Kissen mitbringen.

= render 'info/further_questions'

app/views/info/_map.html.slim
div data-controller='map' data-map-event-id=@event.id
  .map data-target='map.map'
    .popup data-target='map.popup'

app/views/info/_question_answer.html.slim
div data-controller='content-reveal' data-revealed=local_assigns[:revealed]
  a.question.reveal-trigger data-action='content-reveal#reveal'
    = question
  .answer.revealed-content data-target='content-reveal.content'
    div = yield

app/views/info/_questions.html.erb
<div class="trenner"></div>
<div class="section">
  <h2>Meine Frage wurde nicht beantwortet</h2>
  <p>
    Kein Problem! Rufen Sie uns gerne an oder schreiben Sie uns:
  </p>
  <p>
    Telefon: <b>(02653) 28 27 09</b><br>
    e-mail: <%= mail_to 'info@theater-kaisersesch.de' %>
  </p>
</div>

app/views/info/index.html.erb
<% title "Häufig gestellte Fragen" %>
<% include_css "info" %>
<% include_js "info" %>
<div class="hl">
  Häufig gestellte Fragen
</div>

<div class="section">
  <h2>Vorverkauf</h2>

  <div class="question">Wo erhalte ich Tickets?</div>
  <div class="answer">
    Tickets können Sie bequem von zu Hause aus <%= link_to "online", new_ticketing_order_path %> bestellen oder Sie besuchen eine unserer folgenden Vorverkaufsstellen:
    <ul>
      <li>Sportstudio Otto Krechel, Kaisersesch</li>
      <li>Buchhandlung Walgenbach, Kaisersesch</li>
      <li>Buchhandlung Layaa-Laulhé, Cochem</li>
    </ul>
  </div>

  <div class="question">Gibt es Platzreservierungen?</div>
  <div class="answer">Ja, jedes Ticket ist an einen Sitzplatz gebunden, den Sie bei Ihrer Online-Bestellung oder beim Kauf in einer Vorverkaufsstelle anhand unseres Sitzplans frei wählen können.</div>

  <div class="question">Gibt es gehbehindertengerechte Sitzplätze?</div>
  <div class="answer">Ja, bitte melden Sie sich dazu bitte bei unserer Hotline: <b>(02653) 28 27 09</b>.</div>

  <div class="question">Welche Zahlungsarten stehen mir bei der Online-Bestellung zur Verfügung?</div>
  <div class="answer">
    Wir akzeptieren SEPA-Lastschrift und Zahlungen per Überweisung.
    <p>Bei Bestellungen, die weniger als drei Tage vor der gewünschten Aufführung aufgegeben werden, bieten wir Ihnen statt Überweisung auch die Zahlung an der Abendkasse an. Ihre Tickets können hierbei über Ihren Namen oder Ihre Bestellnummer an der Abendkasse abgeholt und bar oder per EC-Karte bezahlt werden.</p>
  </div>

  <div class="question">Wie erhalte ich meine Tickets, die ich online bestellt habe?</div>
  <div class="answer">
    Sofern Sie Zahlung per Lastschrift gewählt haben, werden Ihnen Ihre Tickets umgehend nach Ihrer Bestellung per E-Mail zugesandt. Bei Vorkasse per Überweisung erhalten Sie Ihre Tickets nach Zahlungseingang.
    <p>Im Anhang der E-Mail finden Sie ein PDF-Dokument, das Ihre Tickets enthält. Dieses können Sie sich ausdrucken, um es am Abend der Aufführung bei der Einlasskontrolle vorzuzeigen.</p>
  </div>

  <div class="question">Kann ich meine Tickets auch auf einem Handy vorzeigen?</div>
  <div class="answer">
    Ja, das ist kein Problem. Zeigen Sie dazu einfach das PDF-Dokument auf Ihrem Handy-Display vor.
    <p>Falls Sie ein iPhone besitzen, haben Sie alternativ auch die Möglichkeit, Ihre Tickets in der vorinstallierten App „Wallet“ zu hinterlegen. Nutzen Sie dazu einfach den Button in der Bestätigungs-E-Mail oder scannen Sie mit der genannten App den Barcode auf Ihrem Ticket. Unter Android ist dies mit der App „<%= link_to "Wallet Passes", "https://play.google.com/store/apps/details?id=io.walletpasses.android", target: "_blank" %>“ möglich.</p>
  </div>

  <div class="question">Lassen sich Tickets umbuchen oder stornieren?</div>
  <div class="answer">
    Sie können Ihre Tickets bis 24 Stunden vor Aufführungsbeginn jederzeit umbuchen oder stornieren. Dies gilt auch für Tickets, die in einer Vorverkaufsstelle gekauft wurden. Selbstverständlich erhalten Sie bei einer Stornierung den vollen Betrag der stornierten Tickets zurück.
    <p>Bitte kontaktieren Sie uns hierzu telefonisch: <b>(02653) 28 27 09</b>. In Zukunft werden wir den Umbuchungsservice auch online anbieten.
  </div>
</div>

<div class="trenner"></div>

<div class="section">
  <h2>Anfahrt</h2>

  <div id="map" data-identifier="freilichtbuehne"></div>

  <div class="question">Wo finde ich die Freilichtbühne?</div>
  <div class="answer">
    Unser Freilichttheater findet im Historischen Ortskern von Kaisersesch statt. Dieser befindet sich in der Burgstraße, direkt an der Hauptstraße, bzw. neben der Kirche.
    <p>Im Ort sollte Ihnen unser namensgebender Kirchturm eine gute Orientierungshilfe sein.</p>
  </div>

  <div class="question">Wie reise ich mit dem Auto an?</div>
  <div class="answer">
    Über die Autobahn A48 kommend fahren Sie an der Abfahrt Kaisersesch ab und folgende der Beschilderung bis Kaisersesch. Circa 200 Meter nach Ortseingang finden Sie rechts hinter dem Busbahnhof den Parkplatz „Balduinplatz“.
    <p>Weitere Parkmöglichkeiten sind in der obigen Karte markiert.</p>
  </div>

  <div class="question">Wie reise ich mit öffentlichen Verkehrsmitteln an?</div>
  <div class="answer">
    Möchten Sie mit der Bahn anreisen, fahren Sie von Andernach kommend mit der Regionalbahn der DB Regio bis zum Bahnhof Kaisersesch. Von dort folgen Sie der Bahnhofstraße abwärts in den Ort bis zum Zentralplatz (Sparkasse).
    <p>Mit dem Bus fahren Sie bis zum Balduinplatz.</p>
  </div>
</div>

<div class="trenner"></div>

<div class="section">
  <h2>Wetter</h2>

  <div id="wu">
    <div class="info fadeIn">
      <div class="icon">
        <span class="temp"></span>° C
      </div>
      <div class="data">
        Heute Min: <span class="low"></span>° C | Max: <span class="high"></span>° C
        <br />Regenwahrscheinlichkeit: <span class="pop"></span> %
      </div>
    </div>
    <div class="loader"></div>
    <div class="source fadeIn">
      Das aktuelle Wetter in Kaisersesch, Stand: <span class="date"></span> Uhr&nbsp;
      <%= link_to "http://www.wunderground.com/q/zmw:00000.13.10613", target: "_blank" do %>
        <%= image_tag "info/wunderground.png", alt: "Weather Underground", title: "Wetterdaten zur Verfügung gestellt von Weather Underground" %>
      <% end %>
    </div>
  </div>

  <div class="question">Was passiert, wenn am Aufführungstag schlechtes Wetter herrscht?</div>
  <div class="answer">
    Grundsätzlich versuchen wir bei jeder Wetterlage zu spielen. Sollte das Wetter derart schlecht sein, dass wir die Aufführung schon im Vorfeld absagen oder in der ersten Hälfte des Stücks abbrechen müssen, haben Sie selbstverständlich ein Recht auf Erstattung Ihres Eintrittsgeldes.
    <p>Bitte prüfen Sie an Aufführungstagen mit schlechtem Wetter unsere Homepage, die wir laufend mit aktuellen Informationen versorgen werden.</p>
  </div>

  <div class="question">Sind die Zuschauerränge überdacht?</div>
  <div class="answer">
    Leider nicht. Wir bitten Sie daher, gegebenenfalls an wetterfeste Kleidung zu denken. Gerne erhalten Sie vor Ort aber auch Regenponchos.
  </div>
</div>

<div class="trenner"></div>

<div class="section">
  <h2>Aufführung</h2>

  <div class="question">Ich habe Tickets kurzfristig abzugeben. Kann ich diese an der Abendkasse zurückgeben?</div>
  <div class="answer">Ja, das ist möglich. Sofern wir einen neuen Besitzer für Ihre Tickets finden können, erhalten Sie den vollen Betrag zurück.</div>

  <div class="question">Kann ich an der Abendkasse mit EC- oder Kreditkarte bezahlen?</div>
  <div class="answer">
    Ja, das ist möglich, gerne auch bei kleinen Beträgen. Kontaktlose Zahlungen akzeptieren wir ebenfalls.
    <p>Bitte beachten Sie, dass die Snack- und Getränkestände hingegen nur Bargeld akzeptieren.</p>
  </div>

  <div class="question">Werden vor Ort Speisen und Getränke angeboten?</div>
  <div class="answer">Ja, an unseren Ständen bieten wir gepflegte Getränke und leckere Kleinigkeiten an.</div>

  <div class="question">Wird es eine Pause geben?</div>
  <div class="answer">Nach der ersten Hälfte des Stücks werden wir eine Pause von etwa 20 Minuten einlegen. In dieser Zeit sind unsere Snack- und Getränkestände für Sie geöffnet.</div>

  <div class="question">Wie lange dauert die Aufführung?</div>
  <div class="answer">Wir spielen bis etwa 22.15 Uhr.</div>

  <div class="question">Kann ich während der Aufführung fotografieren oder filmen?</div>
  <div class="answer">Leider können wir Ihnen dies nicht gestatten.</div>

  <div class="question">Gibt es ein Rauchverbot?</div>
  <div class="answer">Während der Aufführung ja, gerne können Sie aber unsere Pause für die ein oder andere Zigarette nutzen.</div>
</div>

<div class="trenner"></div>

<div class="section">
  <h2>Meine Frage wurde nicht beantwortet</h2>
  <p>
    Kein Problem! Rufen Sie uns gerne an oder schreiben Sie uns:
  </p>
  <p>
    Telefon: <b>(02653) 28 27 09</b><br />
    e-mail: <script>document.write(deobfuscate("wiuznfuquow@tzqhqeaqtuuer-zkqawisqeuwrusuesczh.wqqduze"));</script>
  </p>
</div>

app/views/info/map_herdmanns.json.erb
{
  "icons": [
    {
      "name": "theater",
      "offset": [3, 95],
      "file": "<%= asset_path("info/map_marker_theater.png") %>"
    },
    {
      "name": "parking",
      "offset": [3, 35],
      "file": "<%= asset_path("info/map_marker_parking.png") %>"
    }
  ],
  "center": [7.1265, 50.2292],
  "zoom": 16,
  "markers": [
    {
      "loc": [7.1265, 50.2292],
      "icon": "theater",
      "title": "Altes Wasserwerk",
      "desc": "Hier findet die Aufführung statt."
    }
  ]
}

app/views/info/map_sahnemixx.json.erb
{
  "icons": [
    {
      "name": "theater",
      "offset": [3, 95],
      "file": "<%= asset_path("info/map_marker_theater.png") %>"
    },
    {
      "name": "parking",
      "offset": [3, 35],
      "file": "<%= asset_path("info/map_marker_parking.png") %>"
    }
  ],
  "center": [7.13699, 50.23437],
  "zoom": 16,
  "markers": [
    {
      "loc": [7.13739, 50.23529],
      "icon": "parking",
      "title": "Parkplätze",
      "desc": ""
    },
    {
      "loc": [7.13651, 50.23480],
      "icon": "parking",
      "title": "Parkplätze",
      "desc": ""
    },
    {
      "loc": [7.13592, 50.23415],
      "icon": "parking",
      "title": "Parkplätze",
      "desc": ""
    },
    {
      "loc": [7.13699, 50.23437],
      "icon": "theater",
      "title": "Sporthalle",
      "desc": "Hier findet das Konzert statt."
    }
  ]
}